# Streamlit secrets configuration
# Replace these mock values with your actual API keys

[default]
OPENAI_API_KEY = "sk-proj-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
ANTHROPIC_API_KEY = "sk-ant-api03-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
GEMINI_API_KEY = "AIzaSyXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

# Alternative format (if you prefer environment-style):
# OPENAI_API_KEY = "your_actual_openai_key_here"
# ANTHROPIC_API_KEY = "your_actual_anthropic_key_here"
# GEMINI_API_KEY = "your_actual_gemini_key_here" 